name: Test Lint JS
  
  
on: push


jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup
        uses: make setup
      
      - uses: make test
      - uses: make lint
